#### 1. Import NumPy

Make sure to follow the conventions!

In [2]:
import  numpy as np

#### 2. Create an array of 10 zeros

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Expected output

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Expected output

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [ ]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
# Expected output

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create a vector, named `arr`, of 10 zeros the fifth value of which is 1.

In [ ]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# Expected output

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create an array of the integers from 10 to 50

In [ ]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# Expected output

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 7. Reverse an array in **TWO** ways: using 'the Python way' and using a NumPy function

In [ ]:
arr = np.array([1, 2, 3])
print(arr[::-1])
print(np.flip(arr))
# Your code here

[3 2 1]
[3 2 1]


In [ ]:
# Expected output

Using the Python way: [3 2 1]
Using a NumPy function: [3 2 1]


#### 8. Create a 5x5 array with 1 on the border and 0 inside

In [ ]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Expected output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 9. Add a border filled with 0's on the two sides of an array.

> Hint: [np.pad](https://numpy.org/doc/stable/reference/generated/numpy.pad.html)

In [ ]:
arr = np.array([1, 2, 3])
arr = np.pad(arr, 1)
print(arr)


[0 1 2 3 0]


In [ ]:
# Expected output

array([0, 1, 2, 3, 0])

#### 10. Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# Expected output

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 11. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Expected output

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 12. Create a 3x3 identity matrix

In [ ]:
id = np.zeros((3, 3))
np.fill_diagonal(id, 1)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Expected output

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 13. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

> Hint: [np.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

In [ ]:
np.diag([1, 2, 3, 4], k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
# Expected output

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 14. Use NumPy to generate a random number between 0 and 1

**Note**: Your result's value should be different from the one shown below.

In [ ]:
np.random.normal(0, 1, 1)

array([0.32607876])

In [ ]:
# Expected output

array([0.65248055])

#### 15. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

**Note**: Your result's values should be different from the ones shown below.

In [ ]:
np.random.normal(0, 1, 25)

array([-1.20396832,  0.3291865 , -0.0434998 , -0.80233563, -2.456753  ,
       -0.35633998, -0.09282402,  1.80673903,  1.5289614 , -0.41959613,
       -0.07407034,  0.55582317, -0.54219383,  0.03480259, -0.38275321,
        0.36025725,  0.44532519, -1.08919545, -0.26761473,  0.20661532,
       -1.35181033, -0.74230003, -0.09619724,  0.40010924, -1.15861902])

In [ ]:
# Expected output

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 16. Create a 3x3x3 array with random values drawn from the uniform distribution

**Note**: Your result's values should be different from the ones shown below.


In [ ]:
np.random.random((3, 3, 3))

array([[[0.39325051, 0.8368565 , 0.50346396],
        [0.83997348, 0.32225112, 0.47602076],
        [0.20468407, 0.59120717, 0.52128337]],

       [[0.05659684, 0.81398077, 0.40049795],
        [0.98031332, 0.45963914, 0.46119804],
        [0.74349216, 0.02282532, 0.81140827]],

       [[0.47905685, 0.79081544, 0.9920465 ],
        [0.01525542, 0.25207309, 0.05637488],
        [0.10785703, 0.7521961 , 0.19722772]]])

In [ ]:
# Expected output

array([[[0.93641099, 0.2920839 , 0.02292815],
        [0.00336922, 0.86947306, 0.68416644],
        [0.8901026 , 0.3837379 , 0.28653589]],

       [[0.10726099, 0.43744832, 0.00470833],
        [0.29069139, 0.64529908, 0.85020447],
        [0.51284435, 0.41215324, 0.19622211]],

       [[0.43004522, 0.92649706, 0.09472069],
        [0.76510854, 0.49565729, 0.56232861],
        [0.07813665, 0.49086324, 0.45172232]]])

#### 17. Create a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values.

**Note**: Your result's values should be different from the ones shown below.

In [ ]:
random_matrix = np.random.random((10, 10))
np.ndarray.max(random_matrix), np.ndarray.min(random_matrix)

(0.9702482376973613, 0.0067486128372235)

In [ ]:
# Expected output

The array: [[0.19932859 0.92905065 0.55492647 0.09878608 0.0421074  0.74219358
  0.92844055 0.62528946 0.35357668 0.88013918]
 [0.36971412 0.74932736 0.02445995 0.72873717 0.48864481 0.14421664
  0.56846658 0.40363749 0.3233466  0.95147426]
 [0.98339368 0.39612436 0.03609193 0.10611245 0.1410213  0.21099682
  0.3285783  0.39140252 0.88863881 0.81498748]
 [0.25423077 0.0756975  0.77587885 0.29315387 0.56795003 0.90145549
  0.95278316 0.63800115 0.14696466 0.08528442]
 [0.08048731 0.55554534 0.21157669 0.37491896 0.95567126 0.72478012
  0.64849367 0.05571253 0.12339177 0.95575902]
 [0.90842177 0.74316806 0.61710506 0.05885491 0.88051201 0.86814746
  0.26131788 0.89392307 0.45475956 0.26810516]
 [0.79185601 0.19973093 0.10674687 0.9080987  0.50335231 0.17405093
  0.39030326 0.48112173 0.74450033 0.76288692]
 [0.68992283 0.52305591 0.94364282 0.623963   0.04065964 0.23544532
  0.38685327 0.9687442  0.529897   0.37273771]
 [0.88262217 0.90518014 0.24570464 0.49601259 0.23893452 0.53227759
 

#### 18. Create a random array with values drawn from the uniform distribution of size 30 and find the mean value

In [4]:
arr = np.random.uniform(0, 1, 30)
np.mean(arr)

0.5149899714246283

In [ ]:
# Expected output

The array: [0.65580703 0.66012918 0.44607318 0.08230611 0.03965247 0.98197551
 0.07286258 0.08288793 0.5283879  0.26948948 0.29579988 0.44204416
 0.42570657 0.74707057 0.96866384 0.96437312 0.38116077 0.74621085
 0.26497925 0.33115365 0.963408   0.05087827 0.36557266 0.66121816
 0.24851936 0.25971588 0.40104167 0.90926914 0.80488701 0.31365462]
Its mean: 0.4788299599451823


#### 19. Create the following matrix:

In [11]:
np.linspace(0.01, 1, 100).reshape((10, 10))

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# Expected output

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 20. Create an array of 20 linearly spaced points between 0 and 1:

In [8]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# Expected output

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs.

In all of the solutions until the last task before the section `NumPy Operations` you should be using `mat`.

In [12]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 21. Write code that reproduces the output shown below.

In [13]:
# CODE HERE
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Expected output

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 22. Write code that reproduces the output shown below.

In [15]:
mat[3, 4]

20

In [ ]:
# Expected output

20

#### 23. Write code that reproduces the output shown below.

In [19]:
mat[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# Expected output

array([[ 2],
       [ 7],
       [12]])

#### 24. Write code that reproduces the output shown below.

In [20]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
# Expected output

array([21, 22, 23, 24, 25])

#### 25. Write code that reproduces the output shown below.

In [21]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Expected output

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 26. Find the indices of the non-zero elements in the provided array.

In [22]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)
# Your code here

(array([0, 1, 4]),)

In [ ]:
# Expected output

array([0, 1, 4])

## NumPy Operations

#### 27. Get the sum of all the values in mat

In [23]:
np.sum(mat)

325

In [ ]:
# Expected output

325

#### 28. Get the standard deviation of the values in mat

In [24]:
np.std(mat)

7.211102550927978

In [ ]:
# Expected output

7.211102550927978

#### 29. Get the sum of all the columns in mat

In [26]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# Expected output

array([55, 60, 65, 70, 75])

#### 30. Create and multiply a 5x3 matrix by a 3x2 matrix (matrix product). The matrices can hold random values or you can create them manually.

**Note**: In this example output the matrices held random values, so your result's values should be different from the ones shown below.

In [29]:
m1 = np.random.uniform(0, 10, 15).reshape((5, 3))
m2 = np.random.uniform(0, 10, 6).reshape((3, 2))
np.matmul(m1, m2)

array([[ 87.25651831,  69.88006989],
       [ 78.05002638,  73.58544106],
       [105.00559435,  83.47604808],
       [123.43871309, 100.50255524],
       [ 54.03042647,  46.14978366]])

In [ ]:
# Expected output

array([[0.92284566, 0.4834381 ],
       [1.36591969, 0.86692985],
       [0.92732258, 0.57791729],
       [1.20870496, 0.66362074],
       [1.48551291, 0.86352205]])

#### 31. Create a 1D array of random integers between 0 and 9. Negate all elements which are between 3 and 8.

In [40]:
arr = np.random.randint(0, 9, 20)
arr[(arr >= 3 )| (arr <= 8)] *= -1
arr

array([-5, -8, -4,  0,  0, -2, -7,  0,  0, -7, -2, -2, -7, -3, -2, -6, -6,
        0, -4,  0])

In [ ]:
# Expected output

array([ 4,  2,  5, -7, -2,  0, -3, -6, -8,  4])

#### 32. Create a random array of size 10 and sort it

In [42]:
arr = np.random.randint(0, 10, 10)
arr = np.sort(arr)
arr

array([2, 2, 3, 4, 4, 5, 5, 6, 7, 8])

In [ ]:
# Expected output

array([0.21557229, 0.29775351, 0.31513898, 0.48094387, 0.56395818,
       0.61094507, 0.65782361, 0.73666887, 0.74573749, 0.97557176])

#### 33. Create random vector of values drawn from the uniform distribution of size 10 and replace the maximum value by 0

In [45]:
arr = np.random.uniform(0, 1, 10)
arr[np.argmax(arr)] = 0
arr

array([0.0854155 , 0.43085315, 0.10683841, 0.07525426, 0.        ,
       0.664455  , 0.55778053, 0.25226554, 0.53596394, 0.3110222 ])

In [ ]:
# Expected output

The array: [0.79753115 0.51085823 0.86710259 0.25025854 0.39803838 0.65002613
 0.89686752 0.1562022  0.76741728 0.62775096]
Result: [0.79753115 0.51085823 0.86710259 0.25025854 0.39803838 0.65002613
 0.         0.1562022  0.76741728 0.62775096]


#### 34. What function can we use to ensure that we always get the same random numbers?

> **Your answer**: numpy.random.seed(x)
