# Hello, [Tensorflow](https://www.tensorflow.org/api_docs)!

**But what is a tensor?**
 - (for the ML engineer) A tensor is a multidimensional array that can be stored and run on a GPU.
 - (for the mathematician) A generalization of a scalar, vector and matrix:
  - a scalar is a 0D tensor
  - a vector is a 1D tensor
  - a matrix is a 2D tensor

# Imports

In [1]:
%reset -f

In [2]:
import tensorflow as tf

2024-04-25 13:09:25.093667: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-25 13:09:25.097644: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-25 13:09:25.145290: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-25 13:09:25.972699: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


**ALWAYS** check the tensorflow version. It gets updated really, REALLY frequently!

In [3]:
tf.__version__

'2.16.1'

## Initialization of Tensors

### Scalar (0D tensor)

In [35]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [5]:
tf.constant(4.0)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [8]:
tf.constant(4.).numpy()

4.0

### Vector (1D tensor)

In [9]:
tf.constant(4, shape=(1,))

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4], dtype=int32)>

In [10]:
tf.constant(4, shape=(5,))

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 4, 4, 4, 4], dtype=int32)>

In [12]:
tf.constant(4.0, shape=(5,))

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([4., 4., 4., 4., 4.], dtype=float32)>

### Matrix (2D tensor)

In [14]:
tf.constant(4, shape=(4, 4))

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int32)>

In [18]:
tf.constant([[1, 2, 3], [4, 5, 6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [21]:
tf.ones( shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [22]:
tf.zeros(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [26]:
tf.eye(3, 3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

### Sampling from the standard normal distribution

In [27]:
tf.random.normal(shape=(3, 3), mean=0, stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.4216182 , -0.37577975,  0.84051555],
       [ 0.49653605, -1.1894501 , -0.09886509],
       [-0.17154185,  0.04462232,  1.2884513 ]], dtype=float32)>

### Sampling from the uniform distribution

In [30]:
tf.random.uniform(shape=(3, 3), minval=0, maxval=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.74440753, 0.28078854, 0.64098144],
       [0.85093653, 0.16466987, 0.56551564],
       [0.6346805 , 0.47420394, 0.74404395]], dtype=float32)>

### Other useful functions

In [31]:
tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [32]:
tf.range(start=5, limit=10)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([5, 6, 7, 8, 9], dtype=int32)>

In [33]:
tf.range(start=1, limit=10, delta=4)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 5, 9], dtype=int32)>

### Casting

In [36]:
x.dtype

tf.int32

## Mathematical Operations

In [39]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

### Basic

In [40]:
x + y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [41]:
x - y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [42]:
x * y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [43]:
x / y

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [44]:
x / 0

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([inf, inf, inf])>

In [46]:
tf.add(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [47]:
tf.subtract(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [48]:
tf.multiply(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [51]:
tf.divide(x, y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [53]:
x ** 5

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243], dtype=int32)>

### Dot product

In [55]:
# Here, the `axes` parameter specifies along which axis to
# multiply the elements
tf.tensordot(x, y, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [56]:
tf.reduce_sum(x * y)


<tf.Tensor: shape=(), dtype=int32, numpy=46>

### Matrix multiplication

In [57]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

In [58]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.9353757 ,  0.3371497 ,  1.083728  ],
       [-0.6910741 ,  1.0394336 ,  0.25853178]], dtype=float32)>

In [59]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.3028232 , -2.2368913 ,  0.3847311 ,  0.19636919],
       [-1.0305059 ,  1.1041174 , -0.11587885,  1.2649128 ],
       [-0.11859936, -0.7858992 , -0.3890953 , -0.48216364]],
      dtype=float32)>

In [60]:
x @ y

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.19271073,  1.6128857 , -0.8206101 , -0.27974814],
       [-0.8925309 ,  2.4903345 , -0.48691958,  1.0544325 ]],
      dtype=float32)>

In [61]:
tf.matmul(x, y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.19271073,  1.6128857 , -0.8206101 , -0.27974814],
       [-0.8925309 ,  2.4903345 , -0.48691958,  1.0544325 ]],
      dtype=float32)>

## Indexing

In [62]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
x

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3], dtype=int32)>

In [63]:
x[:]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3], dtype=int32)>

In [64]:
x[-3:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [65]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [66]:
x[::2]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 3, 2], dtype=int32)>

In [67]:
x[::-1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([3, 2, 1, 3, 2, 1, 1, 0], dtype=int32)>

## Reshaping

In [74]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [76]:
x = tf.reshape(x, (3, 3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [79]:
x = tf.reshape(x, -1)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>